name: Build and Push Docker Image

on:
  workflow_dispatch: # 只保留手动触发工作流的功能

env:
  IMAGE_NAME: jzho/3x-ui # 你在Docker Hub上的镜像名称 (确认 jzho 是你的用户名)

jobs:
  build-and-push:
    runs-on: ubuntu-latest # 使用最新的Ubuntu runner进行构建

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # 检出你的GitHub仓库代码

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # 设置Docker Buildx，用于更高效的构建

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # 使用设置的Secret
        password: ${{ secrets.DOCKER_PASSWORD }} # 使用设置的Secret

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # Dockerfile和上下文在当前目录
        file: ./Dockerfile # 指定Dockerfile的路径
        push: true # 推送到Docker Hub
        tags: ${{ env.IMAGE_NAME }}:latest # 镜像标签：jzho/sb-sk5:latest
